server:
  command: python src/server.py
  env_file:
    - .env
  image: python:3.4
  working_dir: /mnt
  volumes:
    - .:/mnt
  links:
   - db
  ports:
    - '5000:5000'
  environment:
    OAUTH2_SERVER_DB_CONTAINER: DB
    OAUTH2_SERVER_DB_PW: ''
    OAUTH2_SERVER_DB_USER: root
    OAUTH2_SERVER_PORT: 5000
    IMPORT_PATH: /mnt/test/fixture
    PYTHONPATH: $PYTHONPATH:src:util/src
    PYTHONUSERBASE: /mnt/vendor
    SERVICE_LOG: server.log

db:
  command: mysqld --character-set-server=utf8 --sql_mode="ANSI,ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: oauth2_server
  image: mysql:5.7.16
  volumes:
  - /var/lib/mysql

testserver:
  command: bash -c "sleep 5 && python -m unittest"
  environment:
    PYTHONPATH: $PYTHONPATH:src:test:util/src:util/test
    PYTHONUSERBASE: /mnt/vendor
    OAUTH2_SERVER_DB_CONTAINER: TESTDB
    OAUTH2_SERVER_DB_USER: root
    OAUTH2_SERVER_PORT: 5053
  image: python:3.4
  links:
  - testdb
  ports:
  - 5053:5053
  volumes:
  - .:/mnt
  working_dir: /mnt

testdb:
  command: mysqld --character-set-server=utf8 --sql_mode="ANSI,ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: oauth2_server
  image: mysql:5.7.16
